### ISSUE TITLE
git-pr fails if a remote github repository does not exist

### ISSUE THREAD

**Issue by eserte** [robinsmidsrod/App-GitHubPullRequest#12]
"git pr list" fails if one of a repository's remotes does not exist. To reproduce:

    $ git remote add bogus git://github.com/bogus/bogus

    $ git pr list
    Fetching URL https://api.github.com/repos/bogus/bogus failed with code 404:
    { 
      "message": "Not Found",
      "documentation_url": "http://developer.github.com/v3"
    }

... and there's no pr list printed.

This problem can easily happen if a github account was renamed or
a forked repository removed. In this case additional diagnostics
would be helpful, or the bogus repository could be skipped, with
or without warnings.

**Comment by robinsmidsrod** [comment]
@eserte I decided to solve it in a very simple way. Just try all git remotes in turn until I find one that works. If an invalid git remote is found, emit a warning. This should solve the issue.
