### ISSUE TITLE
'git pr patch <>' Error

### ISSUE THREAD

**Issue by subzerofun** [robinsmidsrod/App-GitHubPullRequest#15]
I can list the prs just fine with `git pr list`, but when i try to patch something i get this error:

```
$ git pr list
Open pull requests for 'TBTerra/spawnScan':
37 2016-08-12T09:50:33Z Auth exception on login.
21 2016-08-10T23:30:38Z Remove .pyc files
$ git pr patch 37
<html><body>You are being <a href="https://patch-diff.githubusercontent.com/raw/TBTerra/spawnScan/pull/37.patch">redirected</a>.</body></html>
```

**Comment by robinsmidsrod** [comment]
Seems like they changed the API somewhat and emit a 3xx redirect for the old API endpoints. If you know, can you figure out what the correct endpoint is for the viewing the patch/diff for a specific PR? Then I will update the URL in the source code. Is it the one mentioned above, or does the API docs say something else?

**Comment by robinsmidsrod** [comment]
@subzerofun Following redirects should solve the issue.
