### ISSUE TITLE
option to keep the upstream protocol for the pr remote

### ISSUE THREAD

**Issue by gaborbernat** [robinsmidsrod/App-GitHubPullRequest#17]
```
stephenfin      git://github.com/stephenfin/tox.git (fetch)
stephenfin      git://github.com/stephenfin/tox.git (push)
upstream        https://github.com/tox-dev/tox.git (fetch)
upstream        https://github.com/tox-dev/tox.git (push)
```

Using this tool you can see the remote generated uses a different protocol (git instead of https). Can we add a configuration/flag/option to keep the same protocol as the upstream has? In some cases (e.g. behind a proxy) you cannot use some protocols.

**Comment by gaborbernat** [comment]
It's indeed what Github returns, and the documentation (https://developer.github.com/v3/pulls/#get-a-single-pull-request) shows no mention how to select. Can we swap the protocol locally before using it though, not?

**Comment by robinsmidsrod** [comment]
@gaborbernat Well, we could try to switch the URL scheme to https if a setting indicating this is set. Would you be willing to try and create a pull request for this?

**Comment by gaborbernat** [comment]
Sadly my Perl knowledge equals heavily to zero; so not sure I could cook up something acceptable :cry:

**Comment by robinsmidsrod** [comment]
@gaborbernat I've pushed release 0.5.0 to CPAN right now, which uses GitHub v3 API clone_url instead of git_url, which should use https URLs in most situations.

**Comment by gaborbernat** [comment]
Just tested it works great for me now! :+1: 

![thank you very much](https://media.tenor.co/images/f29bd274b1239980be41c3f146e0e4e7/tenor.gif)
