### ISSUE TITLE
Enterprise Github support

### ISSUE THREAD

**Issue by gaborbernat** [robinsmidsrod/App-GitHubPullRequest#18]
There's a check that tries to validate if the remote is Github: https://github.com/robinsmidsrod/App-GitHubPullRequest/blob/8736d8ac9975f354425e9943767098244986e5d4/lib/App/GitHubPullRequest.pm#L403

Consider making this check optional (or add option to extend valid URLs with extra ones) in order to support Enterprise Github. I see no reason why all this should/could not work against enterprise installations. An easy workaround is to maybe give the option to specify alternative valid Github in an environment variable?

**Comment by robinsmidsrod** [comment]
@gaborbernat Well, I don't think it's quite that easy. There are several other places where the GitHub API is used with just parts of the git remote URL. Is there another way to validate if a git remote can be accessed using the v3 GitHub API?

**Comment by gaborbernat** [comment]
I think we should see what the git remote is in the current repository and derive the Github API from it. Afterwards, we can try to do a cached (e.g. save a flag to a local file) test call (like fetching the meta https://developer.github.com/v3/meta/) if that passes we can use it.
